### ISSUE TITLE
Scalar list editor

### ISSUE THREAD

**Issue by sorenbs** [graphcool/console#141]
If you open the scalar list editor popup, enter a new value, do not click the plus button, press enter. Then the popup closes, the field will say null and if you open the popup again the following happens:

![image](https://cloud.githubusercontent.com/assets/281337/17833813/5e96b2b8-6728-11e6-8bc3-65d51b391b38.png)

**Comment by brene** [comment]
This is interesting!





On Sat, Aug 20, 2016 at 10:51 PM +0200, "Søren Bramer Schmidt" <notifications@github.com> wrote:





If you open the scalar list editor popup, enter a new value, do not click the plus button, press enter. Then the popup closes, the field will say null and if you open the popup again the following happens:



![image](https://cloud.githubusercontent.com/assets/281337/17833813/5e96b2b8-6728-11e6-8bc3-65d51b391b38.png)


--
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/graphcool/dashboard/issues/141

**Comment by timsuchanek** [comment]
Continuing in #299
