### ISSUE TITLE
Refresh required until auth providers take action

### ISSUE THREAD

**Issue by brene** [graphcool/console#256]
![image](https://cloud.githubusercontent.com/assets/4989523/19271687/0a6e3262-8fc6-11e6-8d9a-bb5e1a7c6119.png)
After clicking "Enable" and closing the window:
![image](https://cloud.githubusercontent.com/assets/4989523/19271706/19b48e4c-8fc6-11e6-9066-c75bedc0c94f.png)
I expect to see the generated fields. But I have to manually refresh to see them.

**Comment by timsuchanek** [comment]
We fixed this now with an ugly hack: Reload
The problem seems to be `react-virtualized`, as even if the props are updated correctly in the `InfiniteTable` component, `react-virtualized` doesn't call the render methods of the 3 `Grid`s we're having.
As we're using `react-virtualized` 7 and 8 is out, an update to 8 might solve this issue.
However, that's a separate issue as in the new version are some breaking changes and the migration seems non-trivial.
